### ISSUE TITLE
AzTS exceptions - System.ArgumentException: Requested value 'CDN' was not found.

### ISSUE THREAD

**Issue by sbgillett** [azsk/DevOpsKit#1377]
## Description</br>
Solution deploys but does not function correctly. Critical exceptions are logged.

## Steps to reproduce
Deploy AzTs (as of [bf3be75][1] as per the readme. 

[1]:https://github.com/azsk/DevOpsKit/commit/bf3be756f566a33f5d95f46b14dbef6ac4c01d0a 

## Expected behavior</br> 
I am able to query scan results by using the example Log Analytics queries and Power BI template provided.

## Actual behavior</br>
Solution appears to have deployed correctly (as in all the functions are present), but PowerBI report template cannot be refreshed (`AzSK_ControlResults_CL` custom log not created) and exceptions are logged as below:

```
System.ArgumentException: Requested value 'CDN' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at Microsoft.AzSK.ATS.ProcessSubscriptions.Processors.ControlEvaluationProcessor.GetAzServiceFlagCodeForControls(List`1 controlList) in D:\a\1\s\src\TenantScan\ProcessSubPolicySummary\Processors\ControlProcessors\ControlEvaluationProcessor.cs:line 228
   at Microsoft.AzSK.ATS.ProcessSubscriptions.Processors.ControlEvaluationProcessor.Process(SubscriptionInventory subscriptionInventory) in D:\a\1\s\src\TenantScan\ProcessSubPolicySummary\Processors\ControlProcessors\ControlEvaluationProcessor.cs:line 85
```

**Comment by ritika-msft** [comment]
We found that there was an issue in one of the packages of the scan solution. We have released fix for this issue, next scheduled scan should happen successfully and you should be able to get the scan results in Log Analytics workspace.

**Note** : Recently we have observed some issues related to AzTS setup due to which function apps inside AzTS setup lack function definition. If you are also facing the same issue, you need to re-run setup command with same parameter.

#Set the context to hosting subscription
Set-AzContext -SubscriptionId <HostingSubId>


2. Run installation command with required parameters given. 

# Step 2: Run installation command. 

Install-AzSKTenantSecuritySolution `
                -SubscriptionId <HostingSubId> `
                -ScanHostRGName <HostingResourceGroupName> `
                -ScanIdentityId <ManagedIdentityResourceId> `
                -Location <ResourceLocation> `
                -Verbose

For more details, please refer [https://github.com/azsk/DevOpsKit-docs/blob/master/13-Tenant%20Security%20Solution%20Setup/Readme.md#setting-up-azure-tenant-security-solution---step-by-step](url)

**Comment by sbgillett** [comment]
Thanks for the reply @ritika-msft 

I reinstalled the solution and no longer get exceptions logged, but not getting any results either. 

In the custom log `AzSK_ProcessedSubscriptions_CL` I see entries with the following comment against each of my target subscriptions:

> Subscription not processed as basic providers are not registered

No further detail than that is provided so it's difficult to troubleshoot. Could you shed any light?
--
